name: Deploy resource infrastructure

parameters:
- name: env
  displayName: 'Environment info'
  type: string


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ parameters.env }}

    steps:
      - uses: actions/checkout@v3

      - name: Print Inputs
        run: |
          echo "Release Type: ${{ parameters.env }}"

      - name: bicep-build-output
        uses: Azure/bicep-build-action@v1.0.1
        with:
          bicepFilePath: ./main.bicep
          outputFilePath: ./azuredeploy.json

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_ARTNOTISER }}

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.9
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: resourcegroup
          # Provide the name of a resource group, only required for resource Group deployments.
          resourceGroupName: artnotiser-dev
          # Specify the path or URL to the Azure Resource Manager template.
          template: ./azuredeploy.json
          deploymentMode: Incremental
          # Supply deployment parameter values.
          parameters: artportalenKey=${{ secrets.ARTNOTISER_ARTPORTALENKEY }} mailerSendToken=${{ secrets.ARTNOTISER_MAILERSENDTOKEN }} environmentPrefix=${{ env.ARTNOTISER_ENVIRONMENTPREFIX }}
